name: papa_johns
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  cupertino_icons: ^1.0.2
  get: ^4.6.5
  dots_indicator: ^3.0.0
  sizer: ^2.0.15
  intl: ^0.18.1
  intl_phone_field: ^3.2.0
  pinput: ^2.3.0
  http: ^1.1.0
  image_picker: ^1.0.2
  permission_handler: ^10.4.3
  path_provider: ^2.1.0
  dio: ^5.3.2
  curved_navigation_bar: ^1.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets: 
    - assets/images/
